import { Platform, StyleSheet } from 'react-native';
import type { ThemeColors } from '@/theme/colors';

export const createSubscriptionFormStyles = (colors: ThemeColors) => StyleSheet.create({
  scrollContent: {
    paddingHorizontal: 20,
    paddingVertical: 24,
    paddingBottom: 160,
  },
  aiScanButton: {
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 20,
    overflow: 'hidden',
    borderRadius: 16,
    backgroundColor: '#6366F1',
    shadowColor: '#6366F1',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  aiScanText: {
    flexShrink: 1,
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '600',
    textAlign: 'center',
  },
  basicInfoHeading: {
    marginBottom: 12,
  },
  basicInfoTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '800',
  },
  basicInfoDescription: {
    marginTop: 3,
    color: colors.textSecondary,
    fontSize: 13,
  },
  fieldSpacing: {
    marginBottom: 16,
  },
  advancedToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
    backgroundColor: colors.surface,
  },
  advancedToggleCopy: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  advancedToggleText: {
    flex: 1,
  },
  advancedToggleTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '800',
  },
  advancedToggleDescription: {
    marginTop: 2,
    color: colors.textSecondary,
    fontSize: 12,
  },
  switchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    backgroundColor: colors.surface,
  },
  switchCopy: {
    flex: 1,
    marginRight: 16,
  },
  switchTitle: {
    marginBottom: 4,
    color: colors.text,
    fontSize: 16,
    fontWeight: '600',
  },
  switchDescription: {
    color: colors.textSecondary,
    fontSize: 14,
  },
  cardTrigger: {
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    backgroundColor: colors.surface,
  },
  cardTriggerText: {
    flex: 1,
    flexShrink: 1,
    color: colors.text,
    fontSize: 15,
    fontWeight: '500',
  },
  fieldLabel: {
    marginBottom: 6,
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  chevron: {
    marginLeft: 12,
    color: colors.textSecondary,
    fontSize: 12,
  },
  splitSection: {
    marginTop: 16,
    marginBottom: 16,
  },
  splitPanel: {
    padding: 16,
    marginTop: 12,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
    backgroundColor: colors.surface,
  },
  equalSplitButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 16,
    overflow: 'hidden',
    borderRadius: 10,
    backgroundColor: `${colors.primary}15`,
  },
  equalSplitText: {
    flexShrink: 1,
    color: colors.primary,
    fontSize: 13,
    fontWeight: '800',
    textAlign: 'center',
  },
  splitMember: {
    paddingBottom: 16,
    marginBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  lastSplitMember: {
    borderBottomWidth: 0,
  },
  splitMemberHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  splitMemberTitle: {
    color: colors.text,
    fontWeight: '700',
  },
  iconButton: {
    padding: 6,
  },
  whatsappButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginTop: 8,
    overflow: 'hidden',
    borderRadius: 8,
    backgroundColor: '#10B98120',
  },
  whatsappText: {
    flexShrink: 1,
    color: '#10B981',
    fontWeight: '700',
    textAlign: 'center',
  },
  addMemberButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: 8,
    borderStyle: 'dashed',
  },
  addMemberText: {
    flexShrink: 1,
    color: colors.primary,
    fontWeight: '700',
    textAlign: 'center',
  },
  buttonGroup: {
    marginTop: 8,
  },
  validationBanner: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginTop: 4,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.danger,
    borderRadius: 12,
    backgroundColor: `${colors.danger}18`,
  },
  validationText: {
    color: colors.danger,
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  deleteButton: {
    marginTop: 12,
  },
  modalInset: {
    paddingBottom: Platform.OS === 'ios' ? 40 : 24,
  },
});
