import { StyleSheet, Text, View, type StyleProp, type ViewStyle } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import type { ThemeColors } from '@/theme/colors';
import type { UpcomingPaymentAnalysis } from '@/features/analytics/utils/financialAnalytics';
import { AnalysisSectionCard, AnalysisSectionHeader } from './AnalysisSectionCard';

export function UpcomingPaymentsSection({ colors, isTurkish, payments, upcomingTotal, formatMoney, formatMonth, onOpenCalendar, style }: { colors: ThemeColors; isTurkish: boolean; payments: UpcomingPaymentAnalysis[]; upcomingTotal: number; formatMoney: (value: number) => string; formatMonth: (date: Date) => string; onOpenCalendar: () => void; style?: StyleProp<ViewStyle> }) {
  return <AnalysisSectionCard surface={colors.surface} border={colors.border} style={style}>
    <AnalysisSectionHeader icon="time-outline" title={isTurkish ? 'Yaklaşan ödemeler' : 'Upcoming payments'} subtitle={isTurkish ? `30 günde ${payments.length > 0 ? formatMoney(upcomingTotal) : 'ödeme yok'}` : `${payments.length > 0 ? formatMoney(upcomingTotal) : 'No payments'} in 30 days`} text={colors.text} secondary={colors.textSecondary} action={isTurkish ? 'Takvim' : 'Calendar'} onAction={onOpenCalendar} />
    {payments.length > 0 ? <View style={styles.list}>{payments.map(payment => <View key={`${payment.subscription.id}-${payment.date.toISOString()}`} style={styles.row}><View style={[styles.badge, { backgroundColor: colors.surfaceSubtle }]}><Text style={[styles.day, { color: colors.text }]}>{payment.date.getDate()}</Text><Text style={[styles.month, { color: colors.textSecondary }]}>{formatMonth(payment.date)}</Text></View><View style={styles.copy}><Text numberOfLines={1} style={[styles.name, { color: colors.text }]}>{payment.subscription.name}</Text><Text style={[styles.timing, { color: colors.textSecondary }]}>{payment.daysLeft === 0 ? (isTurkish ? 'Bugün' : 'Today') : (isTurkish ? `${payment.daysLeft} gün sonra` : `In ${payment.daysLeft} days`)}</Text></View><Text style={[styles.amount, { color: colors.text }]}>{formatMoney(payment.amount)}</Text></View>)}</View> : <View style={styles.empty}><Ionicons name="checkmark-circle-outline" size={25} color="#10B981" /><Text style={[styles.emptyText, { color: colors.textSecondary }]}>{isTurkish ? 'Önümüzdeki 30 günde ödeme görünmüyor.' : 'No payments are due in the next 30 days.'}</Text></View>}
  </AnalysisSectionCard>;
}
const styles = StyleSheet.create({ list: { gap: 5 }, row: { minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: 10 }, badge: { width: 43, height: 43, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, day: { fontSize: 14, fontWeight: '900', lineHeight: 16 }, month: { fontSize: 8, fontWeight: '700', textTransform: 'uppercase' }, copy: { flex: 1 }, name: { fontSize: 12, fontWeight: '800' }, timing: { fontSize: 9, marginTop: 3 }, amount: { fontSize: 12, fontWeight: '900' }, empty: { minHeight: 120, alignItems: 'center', justifyContent: 'center', gap: 10 }, emptyText: { fontSize: 11, textAlign: 'center' } });
