import type { ComponentProps } from 'react';
import { StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import type { ThemeColors } from '@/theme/colors';
type IconName = ComponentProps<typeof Ionicons>['name'];

export function SettingsRow({ colors, icon, iconColor, label, description, value, onPress, showDivider = false }: { colors: ThemeColors; icon: IconName; iconColor: string; label: string; description?: string; value?: string; onPress: () => void; showDivider?: boolean }) {
  return <><TouchableOpacity style={styles.row} activeOpacity={0.7} onPress={onPress}><View style={styles.left}><View style={[styles.icon, { backgroundColor: `${iconColor}1F` }]}><Ionicons name={icon} size={18} color={iconColor} /></View><View style={styles.copy}><Text style={[styles.label, { color: colors.text }]}>{label}</Text>{description ? <Text numberOfLines={2} style={[styles.description, { color: colors.textSecondary }]}>{description}</Text> : null}</View></View><View style={styles.right}>{value ? <Text numberOfLines={1} style={[styles.value, { color: colors.textSecondary }]}>{value}</Text> : null}<Ionicons name="chevron-forward" size={18} color={colors.textSecondary} /></View></TouchableOpacity>{showDivider ? <View style={[styles.divider, { backgroundColor: colors.border }]} /> : null}</>;
}
const styles = StyleSheet.create({ row: { minHeight: 62, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 14, gap: 12 }, left: { flexDirection: 'row', alignItems: 'center', gap: 11, flex: 1 }, icon: { width: 36, height: 36, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, copy: { flex: 1, gap: 2 }, label: { fontSize: 14, fontWeight: '700', flexShrink: 1 }, description: { fontSize: 11, lineHeight: 15 }, right: { flexDirection: 'row', alignItems: 'center', gap: 6, maxWidth: '46%' }, value: { fontSize: 12, fontWeight: '700', flexShrink: 1 }, divider: { height: StyleSheet.hairlineWidth, marginLeft: 61 } });
