import { Modal, Pressable, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import type { ThemeColors } from '@/theme/colors';

export type PickerOption = { value: string; label: string; detail?: string; symbol?: string };
export function SettingsPickerModal({ visible, title, options, selected, colors, bottomPadding, accent, onSelect, onClose }: { visible: boolean; title: string; options: PickerOption[]; selected: string; colors: ThemeColors; bottomPadding: number; accent: string; onSelect: (value: string) => void; onClose: () => void }) {
  return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={styles.overlay}><Pressable style={styles.dismiss} onPress={onClose} /><View style={[styles.content, { backgroundColor: colors.surface, borderColor: colors.border, paddingBottom: bottomPadding }]}><View style={styles.header}><Text style={[styles.title, { color: colors.text }]}>{title}</Text><TouchableOpacity onPress={onClose}><Ionicons name="close-circle" size={23} color={colors.textSecondary} /></TouchableOpacity></View><ScrollView style={styles.scroll}>{options.map(option => { const active = option.value === selected; return <TouchableOpacity key={option.value} style={[styles.option, { backgroundColor: active ? `${accent}1F` : colors.background, borderColor: active ? accent : colors.border }]} onPress={() => onSelect(option.value)}><View style={styles.optionCopy}>{option.symbol ? <View style={[styles.symbol, { backgroundColor: `${accent}1F` }]}><Text style={{ color: accent, fontWeight: '900' }}>{option.symbol}</Text></View> : null}<View style={styles.labels}><Text style={[styles.label, { color: colors.text }]}>{option.label}</Text>{option.detail ? <Text style={[styles.detail, { color: colors.textSecondary }]}>{option.detail}</Text> : null}</View></View>{active ? <Ionicons name="checkmark-circle" size={22} color={accent} /> : null}</TouchableOpacity>; })}</ScrollView></View></View></Modal>;
}
const styles = StyleSheet.create({ overlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,.55)' }, dismiss: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0 }, content: { maxHeight: '76%', borderTopLeftRadius: 26, borderTopRightRadius: 26, borderWidth: 1, padding: 18 }, header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14 }, title: { fontSize: 18, fontWeight: '900' }, scroll: { maxHeight: 420 }, option: { minHeight: 58, borderRadius: 15, borderWidth: 1, paddingHorizontal: 13, marginBottom: 9, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, optionCopy: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 }, symbol: { width: 34, height: 34, borderRadius: 10, alignItems: 'center', justifyContent: 'center' }, labels: { flex: 1 }, label: { fontSize: 14, fontWeight: '800' }, detail: { fontSize: 10, marginTop: 2 } });
