export const testSubscriptions = [
  { name: 'Netflix', category: 'Entertainment', amount: 15.99, currency: 'USD', billingCycle: 'monthly', notes: 'Premium Plan' },
  { name: 'Spotify', category: 'Music', amount: 10.99, currency: 'USD', billingCycle: 'monthly', notes: 'Family Plan' },
  { name: 'Amazon Prime', category: 'Shopping', amount: 139.00, currency: 'USD', billingCycle: 'yearly', notes: 'Includes Prime Video' },
  { name: 'Gym Membership', category: 'Health', amount: 45.00, currency: 'USD', billingCycle: 'monthly', notes: 'Anytime Fitness' },
  { name: 'ChatGPT Plus', category: 'Productivity', amount: 20.00, currency: 'USD', billingCycle: 'monthly', notes: 'OpenAI subscription' },
  { name: 'GitHub Copilot', category: 'Productivity', amount: 100.00, currency: 'USD', billingCycle: 'yearly', notes: 'Annual billing' },
  { name: 'Disney+', category: 'Entertainment', amount: 7.99, currency: 'USD', billingCycle: 'monthly', notes: 'Basic tier' },
  { name: 'Apple One', category: 'Entertainment', amount: 32.95, currency: 'USD', billingCycle: 'monthly', notes: 'Premier plan' },
  { name: 'Vercel', category: 'Software', amount: 20.00, currency: 'USD', billingCycle: 'monthly', notes: 'Pro plan for hosting' },
  { name: '1Password', category: 'Security', amount: 35.88, currency: 'USD', billingCycle: 'yearly', notes: 'Password manager' },
  { name: 'Adobe Creative Cloud', category: 'Software', amount: 54.99, currency: 'USD', billingCycle: 'monthly', notes: 'All Apps' },
  { name: 'Google One', category: 'Storage', amount: 9.99, currency: 'USD', billingCycle: 'monthly', notes: '2TB Storage' },
  { name: 'Notion', category: 'Productivity', amount: 8.00, currency: 'USD', billingCycle: 'monthly', notes: 'Plus plan' },
  { name: 'Figma', category: 'Software', amount: 144.00, currency: 'USD', billingCycle: 'yearly', notes: 'Professional plan' },
  { name: 'YouTube Premium', category: 'Entertainment', amount: 13.99, currency: 'USD', billingCycle: 'monthly', notes: 'No ads' },
  { name: 'Xbox Game Pass', category: 'Gaming', amount: 16.99, currency: 'USD', billingCycle: 'monthly', notes: 'Ultimate tier' },
  { name: 'The New York Times', category: 'News', amount: 4.00, currency: 'USD', billingCycle: 'weekly', notes: 'Digital subscription' },
  { name: 'Duolingo Super', category: 'Education', amount: 83.99, currency: 'USD', billingCycle: 'yearly', notes: 'Language learning' },
  { name: 'Internet Bill', category: 'Utilities', amount: 65.00, currency: 'USD', billingCycle: 'monthly', notes: 'Comcast Xfinity' },
  { name: 'Car Insurance', category: 'Insurance', amount: 120.00, currency: 'USD', billingCycle: 'monthly', notes: 'Geico' },
];
